alaltalk/settings.py
search/functions.py

database 수정

---

poetry.lock
pyproject.toml

channels-redis add 하여 머지 요청드립니다.

[Merge request] poetry add channels-redis

---

chat/views.py
static/css/chat/chat_room.css
templates/chat/chat_list.html
templates/chat/chat_room.html

- DB에 create 할때 객체를 받도록 수정
- 각 채팅방 별 마지막 메세지 출력되도록 구현

[Merge request] modify ChatRoom id to object

---

search/apis/v1/like_cancel_router.py
search/apis/v1/like_router.py
search/apis/v1/schemas/__init__.py
search/apis/v1/schemas/content_request.py
search/apis/v1/schemas/content_response.py
search/models.py
search/service/like_cancel_service.py
search/service/like_service.py

book, shopping 찜하기 찜 취소 - API 기능 완료 했습니다

book , shopping, 찜하기, 찜 취소 추가

---

templates/chat/chat_room.html

- 채팅방 입장시 스크롤 하단 고정상태
- 채팅작성시 스크롤 하단 고정
- 엔터키 입력시 메세지 두번 출력되는 문제 잠정적 해결
(공란을 허용해주고, 기존에 공란시 alert을 없앴음 / 빈 input을 엔터했을 경우 메세지는 출력되거나 DB에 저장되지 않음)

[Merge request] add scrolldown in chat_box & solve enterkey problem

---

static/css/search/recommend.css
static/js/search/recommend.js
templates/search/recommend_include_recommend.html

추천 컨텐츠 스위치 기능 추가

---

templates/search/recommend_include_recommend.html

HTML에서 sty le 태그를 안먹여서 바로 안되는 것같아서 추가해줬습니다!

수정 - HTML 에서 style 태그 추가

---

static/css/search/recommend.css
static/js/base.js
static/js/search/recommend.js
templates/search/recommend_include_recommend.html

keyword 서버 배포 및 연결, 
탭이동 합수 수정, 
채팅 로그 가져오는 함수 연결

keyword 서버 배포 및 연결, 탭이동 합수 수정, 채팅 로그 가져오는 함수 연결

---

static/js/search/recommend.js

js 파일 코드 정리 - 리팩토링은 아직

---

search/apis/v1/schemas/__init__.py
search/apis/v1/schemas/crawling_request.py
search/apis/v1/schemas/crwaling_response.py
search/apis/v1/search_router.py
search/functions.py
search/service/search_service.py
static/js/search/recommend.js
templates/search/recommend_include_recommend.html

검색 API 추가 
리팩토링 진행했습니다
추가적인 버그 있으시면 알려주세요!!

추천기능 리팩토링 했습니다.

---

static/css/search/recommend.css

토글키 위치가 창의 크기에 따라 바뀌여서 위치와 폰트 수정했습니다.

추천시스템 - 토글키 위치,폰트 수정했습니다 ( vw >> px )

---

alaltalk/settings.py
requirements.txt
search/apps.py
search/functions.py

requirements 변경 > @~~~.whl 은 install이안됨
redis > aws와 연결
그외 수정

크롤링 위치 바꾸기  - 함수 호출 때마다

---

alaltalk/settings.py
static/css/accounts/signin.css
static/css/accounts/signup.css
static/css/base.css
static/css/chat/friend_like.css
static/css/landing/landing.css
static/css/search/recommend.css
static/js/landing/landing.js
templates/landing/landing_page.html

[Merge request] final css

---

static/css/accounts/mypage.css
static/css/accounts/user_list.css
static/css/base.css
static/css/chat/chat_room.css
static/css/landing/landing.css
static/css/search/recommend.css
templates/landing/landing_page.html

[Merge request] modify css 11

---

alaltalk/settings.py
static/css/accounts/mypage.css
templates/chat/chat_room.html

- 채팅시 상대방 인풋 내용 사라지지 않게 처리했습니다.

[Merge request] issue # chat input

---

alaltalk/settings.py
chat/urls.py
chat/views.py
static/css/chat/chat_room.css
templates/chat/chat_room.html

- xss 공격 방어 코드 재작성
- 채팅 내용에 마우스 호버시에 타임스탬프 기능 추가

[Merge request] modify xss attack exceptions & timestamp when message mouseovered

---

alaltalk/settings.py
requirements.txt
search/functions.py
search/service/search_service.py
static/js/search/recommend.js
templates/chat/chat_room.html

webdriver종료 코드 추가 

---

crawl_2.py
search/apis/v1/search_router.py
search/functions.py

크롤링 Request 수정!

---

alaltalk/asgi.py
alaltalk/settings.py
search/apis/v1/search_router.py
search/service/search_service.py

book, news 크롤링 함수 리팩토링! 
https 연결

refatoring

---

.gitignore
Dockerfile
Pipfile
Pipfile.lock
alaltalk/asgi.py
alaltalk/enviorment.py
alaltalk/settings/base.py
alaltalk/settings/dev.py
alaltalk/settings/prod.py
alaltalk/wsgi.py
docker-compose.yaml
manage.py
pytest.ini
requirements.txt

- Docker 및 Docker-compose 개발환경설정
- settings 분리 및 환경변수파일 관리
- 인증용 라이브러리 추가 (simple-jwt)

[SETUP] settings 분리 및 docker 환경설정 추가
